name: ccl_ui
description: "CeylonCodeLabs UI Extensions"
version: 0.2.3
homepage: https://github.com/CeylonCodeLabs/ccl_packages
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ccl_services: 
    git:
      url: https://github.com/MrShakila/ccl_packages.git
      ref: framework-agnostic-services
      path: ccl_services
  ccl_core: any
  responsive_builder: ^0.7.0
  stacked: ^3.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^4.0.0

scripts:
  gen_changelog: git-chglog -o CHANGELOG.md
  gen_release_note: git log --pretty="- %s (%an)" $(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1))..HEAD > release_note.txt